# scripts/run_optimization_cf.py
# ─────────────────────────────────────────────────────────────
# Run counterfactual generation via latent space optimization.
#
# Usage :
#   python -m scripts.run_optimization_cf
#   or
#   python scripts/run_optimization_cf.py
#
# No training phase — CFs are generated by running an
# optimization loop per instance at evaluation time.
# ─────────────────────────────────────────────────────────────

import os
import sys
import json

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.utils.config     import load_config
from src.utils.train_tools import get_device
from src.training.optimization_trainer import OptimizationTrainer


# ── Configs ──────────────────────────────────────────────────
CONFIG_FORECASTER = "assets/configs/models/etth1_dataset/itransformer/etth1_96_48_S.json"
CONFIG_AE         = "assets/configs/models/etth1_dataset/ae/tcn_ae.json"
CONFIG_OPT        = "assets/configs/models/etth1_dataset/optimization_strategy/wachter_latent_etth1.json"

N_BATCHES         = 20     # number of test batches to evaluate


# ── Main ─────────────────────────────────────────────────────
if __name__ == "__main__":

    cfg_f   = load_config(CONFIG_FORECASTER)
    cfg_ae  = load_config(CONFIG_AE)
    cfg_opt = load_config(CONFIG_OPT)

    device  = get_device(cfg_f)

    print("=" * 60)
    print("Counterfactual Generation — Wachter Latent")
    print("=" * 60)
    print(f"Device      : {device}")
    print(f"Forecaster  : {CONFIG_FORECASTER}")
    print(f"AE          : {CONFIG_AE}")
    print(f"Config opt  : {CONFIG_OPT}")
    print(f"n_batches   : {N_BATCHES}")
    print("=" * 60)

    trainer = OptimizationTrainer(cfg_f, cfg_ae, cfg_opt, device)
    results = trainer.evaluate(n_batches=N_BATCHES)

    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"  Success rate      : {results['success']*100:.1f}%")
    print(f"  Delta mean        : {results['delta_mean']:.4f}")
    print(f"  Relative reduction: {results['relative_red']*100:.1f}%")
    print(f"  Plausibility (avg): {results['plausibility']:.4f}")
    print(f"    IF              : {results['plaus_if']:.4f}")
    print(f"    LOF             : {results['plaus_lof']:.4f}")
    print(f"    OC-SVM          : {results['plaus_ocsvm']:.4f}")
    print(f"  Time total        : {results['time_total_s']:.1f}s")
    print(f"  Time / batch      : {results['time_per_batch_s']:.2f}s")
    print("=" * 60)
    print(f"\n✅ Done !")
    print(f"  Figures → {cfg_opt.figures_dir}/")
    print(f"  Results → {cfg_opt.results_dir}/wachter_latent_results.json")