// Auto-generated by demo/load_data.py — do not edit manually
const BASELINES_DATA = {
  "etth1": {
    "itransformer": {
      "RL-MCF": {
        "validity_ratio": 0.976,
        "stepwise_auc": 0.9818,
        "proximity_l2": 0.605,
        "compactness": 0.8026,
        "temporal_consistency": 0.9689,
        "plausibility_ensemble": 0.1743,
        "time_ms": 2.0
      },
      "BaseNN": {
        "validity_ratio": 0.5583333373069763,
        "stepwise_auc": 0.5687500238418579,
        "proximity_l2": 2.6579627990722656,
        "compactness": 0.015104166232049465,
        "temporal_consistency": 0.5663964748382568,
        "plausibility_ensemble": 0.13932543992996216,
        "time_ms": 3.0262351036071777
      },
      "BaseGrad": {
        "validity_ratio": 0.4739583432674408,
        "stepwise_auc": 0.484375,
        "proximity_l2": 1.1951591968536377,
        "compactness": 0.01145833358168602,
        "temporal_consistency": 0.6577411890029907,
        "plausibility_ensemble": 0.9199268221855164,
        "time_ms": 5151.798474788666
      },
      "ForecastCF": {
        "validity_ratio": 0.784375011920929,
        "stepwise_auc": 0.792187511920929,
        "proximity_l2": 0.7252072691917419,
        "compactness": 0.01406249962747097,
        "temporal_consistency": 0.7748314142227173,
        "plausibility_ensemble": 0.6416172981262207,
        "time_ms": 6470.589101314545
      }
    },
    "dlinear": {
      "RL-MCF": {
        "validity_ratio": 0.9229,
        "stepwise_auc": 0.9271,
        "proximity_l2": 0.8376,
        "compactness": 0.6781,
        "temporal_consistency": 0.9291,
        "plausibility_ensemble": 0.1761,
        "time_ms": 2.0
      },
      "BaseNN": {
        "validity_ratio": 0.6499999761581421,
        "stepwise_auc": 0.6604166626930237,
        "proximity_l2": 2.9394452571868896,
        "compactness": 0.010937499813735485,
        "temporal_consistency": 0.5595622062683105,
        "plausibility_ensemble": 0.19221416115760803,
        "time_ms": 2.376258373260498
      },
      "BaseGrad": {
        "validity_ratio": 0.9739583134651184,
        "stepwise_auc": 0.9833333492279053,
        "proximity_l2": 0.4271225333213806,
        "compactness": 0.01354166679084301,
        "temporal_consistency": 0.8709529042243958,
        "plausibility_ensemble": 0.43521031737327576,
        "time_ms": 36.48773431777954
      },
      "ForecastCF": {
        "validity_ratio": 0.9281250238418579,
        "stepwise_auc": 0.9307291507720947,
        "proximity_l2": 0.6403215527534485,
        "compactness": 0.014583333395421505,
        "temporal_consistency": 0.781500518321991,
        "plausibility_ensemble": 0.5816918015480042,
        "time_ms": 744.34654712677
      }
    }
  },
  "etth2": {
    "itransformer": {
      "RL-MCF": {
        "validity_ratio": 0.81,
        "stepwise_auc": 0.8171,
        "proximity_l2": 1.2235,
        "compactness": 0.8444,
        "temporal_consistency": 0.9845,
        "plausibility_ensemble": 0.0564,
        "time_ms": 2.0
      },
      "BaseNN": {
        "validity_ratio": 0.9083333611488342,
        "stepwise_auc": 0.9177083373069763,
        "proximity_l2": 5.439417839050293,
        "compactness": 0.0,
        "temporal_consistency": 0.9219931960105896,
        "plausibility_ensemble": 0.10523846000432968,
        "time_ms": 2.3308277130126953
      },
      "BaseGrad": {
        "validity_ratio": 0.28125,
        "stepwise_auc": 0.2916666567325592,
        "proximity_l2": 1.685293197631836,
        "compactness": 0.0036458333488553762,
        "temporal_consistency": 0.7417768836021423,
        "plausibility_ensemble": 0.7676528692245483,
        "time_ms": 2265.3040766716003
      },
      "ForecastCF": {
        "validity_ratio": 0.4989583194255829,
        "stepwise_auc": 0.5088541507720947,
        "proximity_l2": 0.785682201385498,
        "compactness": 0.014583333395421505,
        "temporal_consistency": 0.890377938747406,
        "plausibility_ensemble": 0.5540260672569275,
        "time_ms": 3822.116506099701
      }
    },
    "dlinear": {
      "RL-MCF": {
        "validity_ratio": 0.8296,
        "stepwise_auc": 0.8379,
        "proximity_l2": 1.4282,
        "compactness": 0.6773,
        "temporal_consistency": 0.9803,
        "plausibility_ensemble": 0.0571,
        "time_ms": 2.0
      },
      "BaseNN": {
        "validity_ratio": 0.9010416865348816,
        "stepwise_auc": 0.9104166626930237,
        "proximity_l2": 4.623574256896973,
        "compactness": 0.0,
        "temporal_consistency": 0.923866331577301,
        "plausibility_ensemble": 0.05631014704704285,
        "time_ms": 2.0822882652282715
      },
      "BaseGrad": {
        "validity_ratio": 0.9760416746139526,
        "stepwise_auc": 0.9859374761581421,
        "proximity_l2": 0.5724958181381226,
        "compactness": 0.01770833320915699,
        "temporal_consistency": 0.9286180138587952,
        "plausibility_ensemble": 0.5049189329147339,
        "time_ms": 79.71853017807007
      },
      "ForecastCF": {
        "validity_ratio": 0.9916666746139526,
        "stepwise_auc": 0.9927083253860474,
        "proximity_l2": 0.6520770788192749,
        "compactness": 0.01875000074505806,
        "temporal_consistency": 0.9101194739341736,
        "plausibility_ensemble": 0.5394764542579651,
        "time_ms": 305.63100576400757
      }
    }
  },
  "weather": {
    "itransformer": {
      "RL-MCF": {
        "validity_ratio": 0.8443,
        "stepwise_auc": 0.8484,
        "proximity_l2": 1.2936,
        "compactness": 0.6802,
        "temporal_consistency": 0.8303,
        "plausibility_ensemble": 0.2108,
        "time_ms": 2.0
      },
      "BaseNN": {
        "validity_ratio": 0.909375011920929,
        "stepwise_auc": 0.9143229126930237,
        "proximity_l2": 3.783597230911255,
        "compactness": 0.0010416667209938169,
        "temporal_consistency": 0.6016406416893005,
        "plausibility_ensemble": 0.28775256872177124,
        "time_ms": 14.048564434051514
      },
      "BaseGrad": {
        "validity_ratio": 0.637499988079071,
        "stepwise_auc": 0.6427083611488342,
        "proximity_l2": 1.4292044639587402,
        "compactness": 0.0052083334885537624,
        "temporal_consistency": 0.5485438704490662,
        "plausibility_ensemble": 0.8898457288742065,
        "time_ms": 4757.027900218964
      },
      "ForecastCF": {
        "validity_ratio": 0.9098958373069763,
        "stepwise_auc": 0.9114583134651184,
        "proximity_l2": 0.6775470972061157,
        "compactness": 0.01197916641831398,
        "temporal_consistency": 0.6151384711265564,
        "plausibility_ensemble": 0.5719943642616272,
        "time_ms": 4320.193135738373
      }
    },
    "dlinear": {
      "RL-MCF": {
        "validity_ratio": 0.6609,
        "stepwise_auc": 0.6661,
        "proximity_l2": 0.6144,
        "compactness": 0.9271,
        "temporal_consistency": 0.86,
        "plausibility_ensemble": 0.3068,
        "time_ms": 2.0
      },
      "BaseNN": {
        "validity_ratio": 0.9604166746139526,
        "stepwise_auc": 0.9619791507720947,
        "proximity_l2": 2.078207015991211,
        "compactness": 0.0020833334419876337,
        "temporal_consistency": 0.6857652068138123,
        "plausibility_ensemble": 0.23308253288269043,
        "time_ms": 12.485682964324951
      },
      "BaseGrad": {
        "validity_ratio": 0.9822916388511658,
        "stepwise_auc": 0.987500011920929,
        "proximity_l2": 0.5509486794471741,
        "compactness": 0.01718750037252903,
        "temporal_consistency": 0.6572436094284058,
        "plausibility_ensemble": 0.4795730710029602,
        "time_ms": 137.9825234413147
      },
      "ForecastCF": {
        "validity_ratio": 0.918749988079071,
        "stepwise_auc": 0.9208333492279053,
        "proximity_l2": 0.6813369989395142,
        "compactness": 0.01354166679084301,
        "temporal_consistency": 0.616920530796051,
        "plausibility_ensemble": 0.575083315372467,
        "time_ms": 427.96963453292847
      }
    }
  }
};

const FULL_MODELS_DATA = {
  "etth1": {
    "iTransformer": {
      "validity_ratio": 0.976,
      "stepwise_auc": 0.9818,
      "proximity_l2": 0.605,
      "compactness": 0.8026,
      "temporal_consistency": 0.9689,
      "plausibility_ensemble": 0.1743
    },
    "PatchTST": {
      "validity_ratio": 0.976,
      "stepwise_auc": 0.9776,
      "proximity_l2": 0.6435,
      "compactness": 0.7823,
      "temporal_consistency": 0.9464,
      "plausibility_ensemble": 0.1543
    },
    "TimesNet": {
      "validity_ratio": 0.7813,
      "stepwise_auc": 0.7897,
      "proximity_l2": 0.7011,
      "compactness": 0.6793,
      "temporal_consistency": 0.9071,
      "plausibility_ensemble": 0.2687
    },
    "GRU": {
      "validity_ratio": 0.9396,
      "stepwise_auc": 0.9443,
      "proximity_l2": 0.6744,
      "compactness": 0.6807,
      "temporal_consistency": 0.9311,
      "plausibility_ensemble": 0.2613
    },
    "DLinear": {
      "validity_ratio": 0.9229,
      "stepwise_auc": 0.9271,
      "proximity_l2": 0.8376,
      "compactness": 0.6781,
      "temporal_consistency": 0.9291,
      "plausibility_ensemble": 0.1761
    }
  },
  "etth2": {
    "iTransformer": {
      "validity_ratio": 0.81,
      "stepwise_auc": 0.8171,
      "proximity_l2": 1.2235,
      "compactness": 0.8444,
      "temporal_consistency": 0.9845,
      "plausibility_ensemble": 0.0564
    },
    "PatchTST": {
      "validity_ratio": 0.6675,
      "stepwise_auc": 0.6775,
      "proximity_l2": 1.3282,
      "compactness": 0.7815,
      "temporal_consistency": 0.9844,
      "plausibility_ensemble": 0.0669
    },
    "TimesNet": {
      "validity_ratio": 0.8462,
      "stepwise_auc": 0.8565,
      "proximity_l2": 1.406,
      "compactness": 0.6781,
      "temporal_consistency": 0.9764,
      "plausibility_ensemble": 0.0785
    },
    "GRU": {
      "validity_ratio": 0.695,
      "stepwise_auc": 0.7052,
      "proximity_l2": 1.104,
      "compactness": 0.679,
      "temporal_consistency": 0.982,
      "plausibility_ensemble": 0.0884
    },
    "DLinear": {
      "validity_ratio": 0.8296,
      "stepwise_auc": 0.8379,
      "proximity_l2": 1.4282,
      "compactness": 0.6773,
      "temporal_consistency": 0.9803,
      "plausibility_ensemble": 0.0571
    }
  },
  "weather": {
    "iTransformer": {
      "validity_ratio": 0.8443,
      "stepwise_auc": 0.8484,
      "proximity_l2": 1.2936,
      "compactness": 0.6802,
      "temporal_consistency": 0.8303,
      "plausibility_ensemble": 0.2108
    },
    "PatchTST": {
      "validity_ratio": 0.8208,
      "stepwise_auc": 0.8258,
      "proximity_l2": 1.3003,
      "compactness": 0.7812,
      "temporal_consistency": 0.8111,
      "plausibility_ensemble": 0.1849
    },
    "TimesNet": {
      "validity_ratio": 0.949,
      "stepwise_auc": 0.9534,
      "proximity_l2": 0.7284,
      "compactness": 0.6797,
      "temporal_consistency": 0.8529,
      "plausibility_ensemble": 0.2552
    },
    "GRU": {
      "validity_ratio": 0.5203,
      "stepwise_auc": 0.5253,
      "proximity_l2": 0.3611,
      "compactness": 0.9271,
      "temporal_consistency": 0.9048,
      "plausibility_ensemble": 0.4666
    },
    "DLinear": {
      "validity_ratio": 0.6609,
      "stepwise_auc": 0.6661,
      "proximity_l2": 0.6144,
      "compactness": 0.9271,
      "temporal_consistency": 0.86,
      "plausibility_ensemble": 0.3068
    }
  }
};

const ABLATION_DATA = [
  {
    "name": "RL-MCF (full)",
    "validity_ratio": 0.974,
    "stepwise_auc": 0.979,
    "proximity_l2": 0.605,
    "compactness": 0.802,
    "temporal_consistency": 0.968,
    "plausibility_ensemble": 0.169
  },
  {
    "name": "w/o Proximity",
    "validity_ratio": 0.889,
    "stepwise_auc": 0.934,
    "proximity_l2": 0.811,
    "compactness": 0.79,
    "temporal_consistency": 0.949,
    "plausibility_ensemble": 0.253
  },
  {
    "name": "w/o Mask",
    "validity_ratio": 0.851,
    "stepwise_auc": 0.855,
    "proximity_l2": 2.05,
    "compactness": 0.002,
    "temporal_consistency": 0.642,
    "plausibility_ensemble": 0.45
  },
  {
    "name": "RLP (no policy)",
    "validity_ratio": 0.354,
    "stepwise_auc": 0.363,
    "proximity_l2": 0.585,
    "compactness": 0.844,
    "temporal_consistency": 0.962,
    "plausibility_ensemble": 0.438
  }
];
